FROM python:3.9-slim 

WORKDIR /app

# Installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia i sorgenti e templates
COPY src /app
COPY templates /app/templates

EXPOSE 8001

CMD ["uvicorn", "frontend:app", "--host", "0.0.0.0", "--port", "8001"]

