version: "3.8"

services:
  mariadb:
    image: mariadb:11.1 
    container_name: mariadb 
    environment:
      MYSQL_ROOT_PASSWORD: Paoletto
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: vincenzo
      MYSQL_PASSWORD: Paoletto2
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -pPaoletto"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"  # Porta predefinita di Ollama
    volumes:
      - ./ollama_data:/root/.ollama  # Salva i modelli in modo persistente
    environment:
      - OLLAMA_MODELS=gemma:1b-it-qat  # Forza il download del modello all'avvio
    restart: unless-stopped  # Riavvia automaticamente se crasha
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/requirements.txt:/app/requirements.txt:ro
      - ./frontend/templates:/app/templates  
    ports:
      - "8001:8001"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BASE_URL=http://backend:8003
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8003:8003"
    depends_on:
      mariadb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=vincenzo
      - DB_PASSWORD=Paoletto2
      - DB_NAME=cinema_db
      - OLLAMA_HOST=http://ollama:11434  # URL per connettersi a Ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/docs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s